import deck_analyzer.perks as perks

three_spears = [
    perks.remo_two_minus_1,
    perks.remo_two_minus_1,
    perks.remo_four_plus_0,
    perks.repl_one_plus_0_w_one_plus_2,
    perks.repl_one_plus_0_w_one_plus_2,
    perks.add_two_rolling_plus_1,
    perks.add_two_rolling_plus_1,
    perks.add_three_rolling_plus_0_muddle,
    perks.add_two_rolling_plus_0_pierce_3,
    perks.add_one_rolling_plus_0_stun,
    perks.add_one_rolling_plus_0_add_target,
    perks.add_one_plus_0_refresh_item_self,
    perks.add_one_plus_0_refresh_item_self,
    perks.add_one_plus_0_refresh_item_self,
    perks.ignore_negative_item_and_add_two_plus_1
]

triangles = [
    perks.remo_two_minus_1,
    perks.remo_two_minus_1,
    perks.repl_one_minus_1_w_one_plus_1,
    perks.repl_one_plus_0_w_one_plus_2,
    perks.repl_one_plus_0_w_one_plus_2,
    perks.add_three_plus_0_fire,
    perks.add_three_plus_0_ice,
    perks.add_three_plus_0_air,
    perks.add_three_plus_0_earth,
    perks.repl_two_plus_0_w_one_plus_0_fire_and_one_plus_0_earth,
    perks.repl_two_plus_0_w_one_plus_0_ice_and_one_plus_0_air,
    perks.add_two_plus_1_push_1,
    perks.add_one_plus_1_wound,
    perks.add_one_plus_0_stun,
    perks.add_one_plus_0_add_target
]

diviner = [
    perks.remo_two_minus_1,
    perks.remo_two_minus_1,
    perks.remo_one_minus_2,
    perks.repl_two_plus_1_w_plus_3_shield_1_self,
    perks.repl_two_plus_1_w_plus_3_shield_1_self,
    perks.repl_one_plus_0_w_one_plus_1_shield_1_ally,
    perks.repl_one_plus_0_w_one_plus_2_dark,
    perks.repl_one_plus_0_w_one_plus_2_light,
    perks.repl_one_plus_0_w_one_plus_3_muddle,
    perks.repl_one_plus_0_w_one_plus_2_curse,
    perks.repl_one_plus_0_w_one_plus_2_regenerate_self,
    perks.repl_one_minus_1_w_one_plus_1_heal_2_ally,
    perks.add_two_rolling_plus_0_heal_1_self,
    perks.add_two_rolling_plus_0_curse,
    perks.ignore_negative_scenario_and_add_two_plus_1,
]

demolitionist = [
    perks.remo_four_plus_0,
    perks.remo_two_minus_1,
    perks.remo_two_minus_1,
    perks.remo_one_minus_2_and_one_plus_1,
    perks.repl_one_plus_0_w_one_plus_2_muddle,
    perks.repl_one_plus_0_w_one_plus_2_muddle,
    perks.repl_one_minus_1_w_one_plus_0_poison,
    perks.add_two_plus_2,
    perks.add_two_plus_2,
    perks.repl_one_plus_1_w_one_plus_2_earth,
    perks.repl_one_plus_1_w_one_plus_2_earth,
    perks.repl_one_plus_1_w_one_plus_2_fire,
    perks.repl_one_plus_1_w_one_plus_2_fire,
    perks.add_one_plus_0_damage_adjacent_enemies_1,
    perks.add_one_plus_0_damage_adjacent_enemies_1,
]

hatchet = [
    perks.remo_two_minus_1,
    perks.remo_two_minus_1,
    perks.repl_one_plus_0_w_one_plus_2_muddle,
    perks.repl_one_plus_0_w_one_plus_1_poison,
    perks.repl_one_plus_0_w_one_plus_1_wound,
    perks.repl_one_plus_0_w_one_plus_1_immobilize,
    perks.repl_one_plus_0_w_one_plus_1_push_2,
    perks.repl_one_plus_0_w_one_plus_0_stun,
    perks.repl_one_plus_1_w_one_plus_1_stun,
    perks.add_one_plus_2_air,
    perks.add_one_plus_2_air,
    perks.add_one_plus_2_air,
    perks.repl_one_plus_1_w_one_plus_3,
    perks.repl_one_plus_1_w_one_plus_3,
    perks.repl_one_plus_1_w_one_plus_3,
]

voidwarden = [
    perks.remo_two_minus_1,
    perks.remo_one_minus_2,
    perks.repl_one_plus_0_w_one_plus_1_dark,
    perks.repl_one_plus_0_w_one_plus_1_dark,
    perks.repl_one_plus_0_w_one_plus_1_ice,
    perks.repl_one_plus_0_w_one_plus_1_ice,
    perks.repl_one_minus_1_w_one_plus_0_heal_1_ally,
    perks.repl_one_minus_1_w_one_plus_0_heal_1_ally,
    perks.add_one_plus_1_heal_1_ally,
    perks.add_one_plus_1_heal_1_ally,
    perks.add_one_plus_1_heal_1_ally,
    perks.add_one_plus_1_poison,
    perks.add_one_plus_3,
    perks.add_one_plus_1_curse,
    perks.add_one_plus_1_curse,
]

red_guard = [
    perks.remo_four_plus_0,
    perks.remo_two_minus_1,
    perks.remo_one_minus_2_and_one_plus_1,
    perks.repl_one_minus_1_w_one_plus_1,
    perks.repl_one_minus_1_w_one_plus_1,
    perks.repl_one_plus_1_w_one_plus_2_fire,
    perks.repl_one_plus_1_w_one_plus_2_fire,
    perks.repl_one_plus_1_w_one_plus_2_light,
    perks.repl_one_plus_1_w_one_plus_2_light,
    perks.add_one_plus_1_fire_and_light,
    perks.add_one_plus_1_fire_and_light,
    perks.add_one_plus_1_shield_1_self,
    perks.add_one_plus_1_shield_1_self,
    perks.repl_one_plus_0_w_one_plus_1_immobilize,
    perks.repl_one_plus_0_w_one_plus_1_wound,
]

banner_spear = [
    perks.remo_four_plus_0,
    perks.remo_two_minus_1,
    perks.repl_one_minus_1_w_one_plus_1,
    perks.repl_one_minus_2_w_one_plus_0,
    perks.add_two_rolling_plus_0_pierce_3,
    perks.add_two_rolling_plus_0_pierce_3,
    perks.add_two_rolling_plus_1,
    perks.add_two_rolling_plus_1,
    perks.add_two_rolling_plus_0_heal_1_self,
    perks.add_two_rolling_plus_0_heal_1_self,
    perks.add_one_plus_1_shield_1_self,
    perks.add_one_plus_1_shield_1_self,
    perks.add_one_plus_1_wound,
    perks.add_one_plus_1_wound,
    perks.ignore_negative_item_and_remo_one_minus_1,
]

blink_blade = [
    perks.remo_four_plus_0,
    perks.remo_two_minus_1,
    perks.remo_two_minus_1,
    perks.repl_one_plus_0_w_one_plus_2,
    perks.repl_one_minus_1_w_one_plus_1,
    perks.repl_one_minus_2_w_one_plus_0,
    perks.add_one_minus_1_add_bb_counter,
    perks.add_one_minus_1_add_bb_counter,
    perks.add_one_plus_1_regenerate_self,
    perks.add_one_plus_1_regenerate_self,
    perks.add_three_rolling_plus_0_muddle,
    perks.add_three_rolling_plus_0_muddle,
    perks.add_one_plus_1_immobilize,
    perks.add_one_plus_1_immobilize,
    perks.ignore_negative_scenario_and_remo_two_plus_0,
]

deathwalker = [
    perks.remo_two_minus_1,
    perks.repl_one_minus_1_w_one_plus_1,
    perks.repl_one_minus_1_w_one_plus_1,
    perks.repl_one_minus_1_w_one_plus_1,
    perks.repl_one_minus_2_w_one_minus_1_and_one_plus_1,
    perks.add_two_plus_1,
    perks.add_two_plus_1,
    perks.add_three_rolling_plus_0_push_1,
    perks.add_two_rolling_plus_0_wound,
    perks.add_two_rolling_plus_0_wound,
    perks.add_one_rolling_plus_0_heal_2_ally,
    perks.add_one_rolling_plus_0_heal_2_ally,
    perks.add_one_plus_2_dark,
    perks.add_one_plus_2_dark,
    perks.ignore_negative_scenario_and_remo_one_minus_1,
]

drifter = [
    perks.remo_four_plus_0,
    perks.remo_two_minus_1,
    perks.remo_two_minus_1,
    perks.remo_one_minus_2,
    perks.add_two_plus_1,
    perks.add_two_rolling_plus_0_pierce_3,
    perks.add_two_rolling_plus_0_pierce_3,
    perks.add_three_rolling_plus_0_push_1,
    perks.add_three_rolling_plus_0_push_1,
    perks.add_three_rolling_plus_0_muddle,
    perks.add_three_rolling_plus_0_muddle,
    perks.add_one_rolling_plus_0_token_back_one,
    perks.add_one_rolling_plus_0_token_back_one,
    perks.ignore_negative_scenario_and_add_one_plus_1,
    perks.ignore_negative_item_and_add_one_plus_1,
]

geminate = [
    perks.remo_two_minus_1,
    perks.repl_one_minus_2_w_one_minus_1_and_one_rolling_plus_0_pierce_2,
    perks.repl_one_plus_0_w_one_rolling_plus_1,
    perks.repl_one_plus_0_w_one_rolling_plus_1,
    perks.repl_one_plus_0_w_one_plus_1_poison,
    perks.repl_one_plus_0_w_one_plus_1_poison,
    perks.repl_one_plus_0_w_one_plus_1_wound,
    perks.repl_one_plus_0_w_one_plus_1_wound,
    perks.repl_one_minus_1_w_plus_0_consume_anye_infuse_anye,
    perks.repl_one_minus_1_w_plus_0_consume_anye_infuse_anye,
    perks.repl_one_minus_1_w_plus_0_consume_anye_infuse_anye,
    perks.repl_one_plus_1_w_one_plus_3,
    perks.add_two_plus_1_push_1,
    perks.add_one_rolling_plus_0_regenerate_self,
    perks.ignore_negative_scenario_and_add_one_plus_1,
]

necromancer = [
    perks.remo_two_minus_1,
    perks.remo_two_minus_1,
    perks.remo_one_minus_2,
    perks.repl_one_plus_0_w_one_plus_1_earth,
    perks.repl_one_plus_0_w_one_plus_1_earth,
    perks.repl_one_plus_0_w_one_plus_1_dark,
    perks.repl_one_plus_0_w_one_plus_1_dark,
    perks.add_one_plus_1_heal_1_self,
    perks.add_one_plus_1_heal_1_self,
    perks.add_one_plus_1_heal_1_self,
    perks.add_one_plus_1_heal_1_self,
    perks.add_two_rolling_plus_0_poison,
    perks.add_one_plus_3,
    perks.add_one_plus_1_curse,
    perks.add_one_plus_1_curse,
]
